# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(638, 240)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Titre_app = QtWidgets.QLabel(self.centralwidget)
        self.Titre_app.setGeometry(QtCore.QRect(130, 20, 421, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Titre_app.setFont(font)
        self.Titre_app.setAlignment(QtCore.Qt.AlignCenter)
        self.Titre_app.setObjectName("Titre_app")
        self.B_livres = QtWidgets.QPushButton(self.centralwidget)
        self.B_livres.setGeometry(QtCore.QRect(40, 100, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.B_livres.setFont(font)
        self.B_livres.setObjectName("B_livres")
        self.B_lecteurs = QtWidgets.QPushButton(self.centralwidget)
        self.B_lecteurs.setGeometry(QtCore.QRect(230, 100, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.B_lecteurs.setFont(font)
        self.B_lecteurs.setObjectName("B_lecteurs")
        self.B_emprunts = QtWidgets.QPushButton(self.centralwidget)
        self.B_emprunts.setGeometry(QtCore.QRect(420, 100, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.B_emprunts.setFont(font)
        self.B_emprunts.setObjectName("B_emprunts")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 638, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Gestion d'une bibliotheque", "Gestion d'une bibliotheque"))
        self.Titre_app.setText(_translate("MainWindow", "Gestion d\'une bibliothèque"))
        self.B_livres.setText(_translate("MainWindow", "Gestion des livres"))
        self.B_lecteurs.setText(_translate("MainWindow", "Gestion des lecteurs"))
        self.B_emprunts.setText(_translate("MainWindow", "Gestion des emprunts"))


