# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ajout_emprunt.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(555, 272)
        Dialog.setModal(True)
        self.Titre_livre_label_2 = QtWidgets.QLabel(Dialog)
        self.Titre_livre_label_2.setGeometry(QtCore.QRect(80, 50, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Titre_livre_label_2.setFont(font)
        self.Titre_livre_label_2.setObjectName("Titre_livre_label_2")
        self.Id_lecteur_textEdit = QtWidgets.QTextEdit(Dialog)
        self.Id_lecteur_textEdit.setEnabled(False)
        self.Id_lecteur_textEdit.setGeometry(QtCore.QRect(260, 100, 201, 31))
        self.Id_lecteur_textEdit.setObjectName("Id_lecteur_textEdit")
        self.Recherche_emprunt_livre = QtWidgets.QPushButton(Dialog)
        self.Recherche_emprunt_livre.setGeometry(QtCore.QRect(140, 180, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Recherche_emprunt_livre.setFont(font)
        self.Recherche_emprunt_livre.setObjectName("Recherche_emprunt_livre")
        self.Id_lecteur_label = QtWidgets.QLabel(Dialog)
        self.Id_lecteur_label.setGeometry(QtCore.QRect(80, 100, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Id_lecteur_label.setFont(font)
        self.Id_lecteur_label.setObjectName("Id_lecteur_label")
        self.Valider_emprunt_livre = QtWidgets.QPushButton(Dialog)
        self.Valider_emprunt_livre.setEnabled(False)
        self.Valider_emprunt_livre.setGeometry(QtCore.QRect(290, 180, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Valider_emprunt_livre.setFont(font)
        self.Valider_emprunt_livre.setObjectName("Valider_emprunt_livre")
        self.Titre_livre_textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.Titre_livre_textEdit_2.setEnabled(True)
        self.Titre_livre_textEdit_2.setGeometry(QtCore.QRect(250, 50, 211, 31))
        self.Titre_livre_textEdit_2.setObjectName("Titre_livre_textEdit_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Titre_livre_label_2.setText(_translate("Dialog", "Titre du livre"))
        self.Recherche_emprunt_livre.setText(_translate("Dialog", "Rechercher"))
        self.Id_lecteur_label.setText(_translate("Dialog", "Identifiant du lecteur"))
        self.Valider_emprunt_livre.setText(_translate("Dialog", "Valider"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
