# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maj_livre.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(555, 393)
        Dialog.setModal(True)
        self.Titre_livre_textEdit = QtWidgets.QTextEdit(Dialog)
        self.Titre_livre_textEdit.setEnabled(False)
        self.Titre_livre_textEdit.setGeometry(QtCore.QRect(190, 90, 201, 31))
        self.Titre_livre_textEdit.setObjectName("Titre_livre_textEdit")
        self.exemp_livre_label = QtWidgets.QLabel(Dialog)
        self.exemp_livre_label.setGeometry(QtCore.QRect(60, 190, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.exemp_livre_label.setFont(font)
        self.exemp_livre_label.setObjectName("exemp_livre_label")
        self.Auteur_livre_textEdit = QtWidgets.QTextEdit(Dialog)
        self.Auteur_livre_textEdit.setEnabled(False)
        self.Auteur_livre_textEdit.setGeometry(QtCore.QRect(190, 140, 201, 31))
        self.Auteur_livre_textEdit.setObjectName("Auteur_livre_textEdit")
        self.Id_livre_label = QtWidgets.QLabel(Dialog)
        self.Id_livre_label.setGeometry(QtCore.QRect(60, 39, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Id_livre_label.setFont(font)
        self.Id_livre_label.setObjectName("Id_livre_label")
        self.Exemp_spinBox = QtWidgets.QSpinBox(Dialog)
        self.Exemp_spinBox.setEnabled(False)
        self.Exemp_spinBox.setGeometry(QtCore.QRect(190, 190, 42, 22))
        self.Exemp_spinBox.setMinimum(1)
        self.Exemp_spinBox.setMaximum(5)
        self.Exemp_spinBox.setObjectName("Exemp_spinBox")
        self.Valider_maj_livre = QtWidgets.QPushButton(Dialog)
        self.Valider_maj_livre.setEnabled(False)
        self.Valider_maj_livre.setGeometry(QtCore.QRect(300, 320, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Valider_maj_livre.setFont(font)
        self.Valider_maj_livre.setObjectName("Valider_maj_livre")
        self.Auteur_livre_label = QtWidgets.QLabel(Dialog)
        self.Auteur_livre_label.setGeometry(QtCore.QRect(60, 139, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Auteur_livre_label.setFont(font)
        self.Auteur_livre_label.setObjectName("Auteur_livre_label")
        self.Titre_livre_label = QtWidgets.QLabel(Dialog)
        self.Titre_livre_label.setGeometry(QtCore.QRect(60, 89, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Titre_livre_label.setFont(font)
        self.Titre_livre_label.setObjectName("Titre_livre_label")
        self.Id_livre_textEdit = QtWidgets.QTextEdit(Dialog)
        self.Id_livre_textEdit.setEnabled(True)
        self.Id_livre_textEdit.setGeometry(QtCore.QRect(190, 40, 201, 31))
        self.Id_livre_textEdit.setObjectName("Id_livre_textEdit")
        self.Dispo_spinBox = QtWidgets.QSpinBox(Dialog)
        self.Dispo_spinBox.setEnabled(False)
        self.Dispo_spinBox.setGeometry(QtCore.QRect(190, 240, 42, 22))
        self.Dispo_spinBox.setMinimum(1)
        self.Dispo_spinBox.setMaximum(5)
        self.Dispo_spinBox.setObjectName("Dispo_spinBox")
        self.dispo_livre_label = QtWidgets.QLabel(Dialog)
        self.dispo_livre_label.setGeometry(QtCore.QRect(60, 240, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dispo_livre_label.setFont(font)
        self.dispo_livre_label.setObjectName("dispo_livre_label")
        self.Recherche_maj_livre = QtWidgets.QPushButton(Dialog)
        self.Recherche_maj_livre.setGeometry(QtCore.QRect(130, 320, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Recherche_maj_livre.setFont(font)
        self.Recherche_maj_livre.setObjectName("Recherche_maj_livre")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.exemp_livre_label.setText(_translate("Dialog", "Exemplaires"))
        self.Id_livre_label.setText(_translate("Dialog", "Identifiant"))
        self.Valider_maj_livre.setText(_translate("Dialog", "Valider"))
        self.Auteur_livre_label.setText(_translate("Dialog", "Auteur"))
        self.Titre_livre_label.setText(_translate("Dialog", "Titre"))
        self.dispo_livre_label.setText(_translate("Dialog", "Disponibles"))
        self.Recherche_maj_livre.setText(_translate("Dialog", "Rechercher"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
