# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu_gestion_emprunts.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(445, 397)
        Dialog.setModal(True)
        self.Supp_emprunt = QtWidgets.QPushButton(Dialog)
        self.Supp_emprunt.setGeometry(QtCore.QRect(100, 190, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Supp_emprunt.setFont(font)
        self.Supp_emprunt.setObjectName("Supp_emprunt")
        self.Ajout_emprunt = QtWidgets.QPushButton(Dialog)
        self.Ajout_emprunt.setGeometry(QtCore.QRect(100, 120, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Ajout_emprunt.setFont(font)
        self.Ajout_emprunt.setObjectName("Ajout_emprunt")
        self.Liste_emprunts = QtWidgets.QPushButton(Dialog)
        self.Liste_emprunts.setGeometry(QtCore.QRect(100, 260, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Liste_emprunts.setFont(font)
        self.Liste_emprunts.setObjectName("Liste_emprunts")
        self.Menu_livre = QtWidgets.QLabel(Dialog)
        self.Menu_livre.setGeometry(QtCore.QRect(0, 20, 421, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Menu_livre.setFont(font)
        self.Menu_livre.setAlignment(QtCore.Qt.AlignCenter)
        self.Menu_livre.setObjectName("Menu_livre")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Supp_emprunt.setText(_translate("Dialog", "Retour d\'un livre"))
        self.Ajout_emprunt.setText(_translate("Dialog", "Emprunt d\'un livre"))
        self.Liste_emprunts.setText(_translate("Dialog", "Liste des emprunts"))
        self.Menu_livre.setText(_translate("Dialog", "Gestion des emprunts"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
