# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu_gestion_lecteurs.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(444, 397)
        Dialog.setModal(True)
        self.Maj_lecteur = QtWidgets.QPushButton(Dialog)
        self.Maj_lecteur.setGeometry(QtCore.QRect(110, 150, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Maj_lecteur.setFont(font)
        self.Maj_lecteur.setObjectName("Maj_lecteur")
        self.Listes_lecteurs = QtWidgets.QPushButton(Dialog)
        self.Listes_lecteurs.setGeometry(QtCore.QRect(110, 290, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Listes_lecteurs.setFont(font)
        self.Listes_lecteurs.setObjectName("Listes_lecteurs")
        self.Ajout_lecteur = QtWidgets.QPushButton(Dialog)
        self.Ajout_lecteur.setGeometry(QtCore.QRect(110, 80, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Ajout_lecteur.setFont(font)
        self.Ajout_lecteur.setObjectName("Ajout_lecteur")
        self.Supp_lecteur = QtWidgets.QPushButton(Dialog)
        self.Supp_lecteur.setGeometry(QtCore.QRect(110, 220, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Supp_lecteur.setFont(font)
        self.Supp_lecteur.setObjectName("Supp_lecteur")
        self.Menu_lecteur = QtWidgets.QLabel(Dialog)
        self.Menu_lecteur.setGeometry(QtCore.QRect(10, 0, 421, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Menu_lecteur.setFont(font)
        self.Menu_lecteur.setAlignment(QtCore.Qt.AlignCenter)
        self.Menu_lecteur.setObjectName("Menu_lecteur")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Maj_lecteur.setText(_translate("Dialog", "Mise à jour d\'un lecteur"))
        self.Listes_lecteurs.setText(_translate("Dialog", "Liste des lecteurs"))
        self.Ajout_lecteur.setText(_translate("Dialog", "Ajout d\'un lecteur"))
        self.Supp_lecteur.setText(_translate("Dialog", "Suppression d\'un lecteur"))
        self.Menu_lecteur.setText(_translate("Dialog", "Gestion des lecteurs"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
