# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu_gestion_livres.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(445, 397)
        Dialog.setModal(True)
        self.Menu_livre = QtWidgets.QLabel(Dialog)
        self.Menu_livre.setGeometry(QtCore.QRect(10, 0, 421, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Menu_livre.setFont(font)
        self.Menu_livre.setAlignment(QtCore.Qt.AlignCenter)
        self.Menu_livre.setObjectName("Menu_livre")
        self.Supp_livre = QtWidgets.QPushButton(Dialog)
        self.Supp_livre.setGeometry(QtCore.QRect(110, 220, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Supp_livre.setFont(font)
        self.Supp_livre.setObjectName("Supp_livre")
        self.Ajout_livre = QtWidgets.QPushButton(Dialog)
        self.Ajout_livre.setGeometry(QtCore.QRect(110, 80, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Ajout_livre.setFont(font)
        self.Ajout_livre.setObjectName("Ajout_livre")
        self.Maj_livre = QtWidgets.QPushButton(Dialog)
        self.Maj_livre.setGeometry(QtCore.QRect(110, 150, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Maj_livre.setFont(font)
        self.Maj_livre.setObjectName("Maj_livre")
        self.Livres_dispo = QtWidgets.QPushButton(Dialog)
        self.Livres_dispo.setGeometry(QtCore.QRect(110, 290, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Livres_dispo.setFont(font)
        self.Livres_dispo.setObjectName("Livres_dispo")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Menu_livre.setText(_translate("Dialog", "Gestion des livres"))
        self.Supp_livre.setText(_translate("Dialog", "Suppression d\'un livre"))
        self.Ajout_livre.setText(_translate("Dialog", "Ajout d\'un livre"))
        self.Maj_livre.setText(_translate("Dialog", "Mise à jour d\'un livre "))
        self.Livres_dispo.setText(_translate("Dialog", "Liste des livres disponibles"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
