# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'retour_emprunt.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(504, 263)
        Dialog.setModal(True)
        self.Id_livre_label = QtWidgets.QLabel(Dialog)
        self.Id_livre_label.setGeometry(QtCore.QRect(60, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Id_livre_label.setFont(font)
        self.Id_livre_label.setObjectName("Id_livre_label")
        self.Valider_retour_emprunt = QtWidgets.QPushButton(Dialog)
        self.Valider_retour_emprunt.setEnabled(True)
        self.Valider_retour_emprunt.setGeometry(QtCore.QRect(190, 180, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Valider_retour_emprunt.setFont(font)
        self.Valider_retour_emprunt.setObjectName("Valider_retour_emprunt")
        self.Id_livre_textEdit = QtWidgets.QTextEdit(Dialog)
        self.Id_livre_textEdit.setEnabled(True)
        self.Id_livre_textEdit.setGeometry(QtCore.QRect(240, 50, 201, 31))
        self.Id_livre_textEdit.setObjectName("Id_livre_textEdit")
        self.Id_lecteur_label = QtWidgets.QLabel(Dialog)
        self.Id_lecteur_label.setGeometry(QtCore.QRect(60, 100, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Id_lecteur_label.setFont(font)
        self.Id_lecteur_label.setObjectName("Id_lecteur_label")
        self.Id_lecteur_textEdit = QtWidgets.QTextEdit(Dialog)
        self.Id_lecteur_textEdit.setEnabled(True)
        self.Id_lecteur_textEdit.setGeometry(QtCore.QRect(240, 100, 201, 31))
        self.Id_lecteur_textEdit.setObjectName("Id_lecteur_textEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Id_livre_label.setText(_translate("Dialog", "Identifiant"))
        self.Valider_retour_emprunt.setText(_translate("Dialog", "Valider"))
        self.Id_lecteur_label.setText(_translate("Dialog", "Identifiant du lecteur"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
