# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'supp_livre.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 298)
        Dialog.setModal(True)
        self.Id_livre_textEdit = QtWidgets.QTextEdit(Dialog)
        self.Id_livre_textEdit.setEnabled(True)
        self.Id_livre_textEdit.setGeometry(QtCore.QRect(150, 90, 201, 31))
        self.Id_livre_textEdit.setObjectName("Id_livre_textEdit")
        self.Id_livre_label = QtWidgets.QLabel(Dialog)
        self.Id_livre_label.setGeometry(QtCore.QRect(50, 90, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Id_livre_label.setFont(font)
        self.Id_livre_label.setObjectName("Id_livre_label")
        self.Valider_supp_livre = QtWidgets.QPushButton(Dialog)
        self.Valider_supp_livre.setGeometry(QtCore.QRect(150, 190, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Valider_supp_livre.setFont(font)
        self.Valider_supp_livre.setObjectName("Valider_supp_livre")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Id_livre_label.setText(_translate("Dialog", "Identifiant"))
        self.Valider_supp_livre.setText(_translate("Dialog", "Valider"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
