# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'supp_lecteur.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 279)
        Dialog.setModal(True)
        self.Valider_supp_lecteur = QtWidgets.QPushButton(Dialog)
        self.Valider_supp_lecteur.setGeometry(QtCore.QRect(170, 190, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Valider_supp_lecteur.setFont(font)
        self.Valider_supp_lecteur.setObjectName("Valider_supp_lecteur")
        self.Id_lecteur_label = QtWidgets.QLabel(Dialog)
        self.Id_lecteur_label.setGeometry(QtCore.QRect(50, 90, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Id_lecteur_label.setFont(font)
        self.Id_lecteur_label.setObjectName("Id_lecteur_label")
        self.Id_lecteur_textEdit = QtWidgets.QTextEdit(Dialog)
        self.Id_lecteur_textEdit.setEnabled(True)
        self.Id_lecteur_textEdit.setGeometry(QtCore.QRect(180, 91, 201, 31))
        self.Id_lecteur_textEdit.setObjectName("Id_lecteur_textEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Valider_supp_lecteur.setText(_translate("Dialog", "Valider"))
        self.Id_lecteur_label.setText(_translate("Dialog", "Identifiant"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
